@extends('layouts.default')
@section('content')
<header>

<div class="header_top"><div class="wrapper"><div class="header_top1"><div class="logo"><img src="images/logo.png" alt="Ring Tone Creator"></div><span class="make_ringtone">{{dictionary(Session::get('lang'))['top_text']}}</span><div class="country_main"><span class="language">Language</span>
               <select name="countries" id="countries" onChange="changeLanguage(this.value)">
                   <option value='us' {{languageSet('us')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag us" data-title="EN">EN</option>
                   <option value='zh' {{languageSet('zh')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag cn" data-title="ZH">ZH</option>
                   <option value='es' {{languageSet('es')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag es" data-title="ES">ES</option>
                   <option value='pt' {{languageSet('pt')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag pt" data-title="PT">PT</option>
                   <option value='ru' {{languageSet('ru')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag ru" data-title="RU">RU</option>
                   <option value='id' {{languageSet('id')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag id" data-title="ID">ID</option>
                   <option value='fr' {{languageSet('fr')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag fr" data-title="FR">FR</option>
                   <option value='de' {{languageSet('de')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag de" data-title="DE">DE</option>
                   <option value='ja' {{languageSet('ja')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag it" data-title="JA">JA</option>
                   <option value='nl' {{languageSet('nl')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag nl" data-title="NL">NL</option>
                   <option value='pl' {{languageSet('pl')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag pl" data-title="PL">PL</option>
                   <option value='tr' {{languageSet('tr')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag tr" data-title="TR">TR</option>
                   <option value='ko' {{languageSet('ko')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag ko" data-title="KO">KO</option>
                   <option value='it' {{languageSet('it')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag az " data-title="IT">IT</option>
                   <option value='vi' {{languageSet('vi')}} data-image="images/ringtonemaker/blank.gif" data-imagecss="flag vi" data-title="VI">VI</option>
                </select>
        	</div></div></div></div></header><div class="content"> <div class="banner"> <div class="wrapper"> <h1 class="banner_text">FREE RINGTONE CREATOR</h1> </div></div><div class="banr_aftr_sec"> <div class="ringtone_left"> <h2 class="ringtone_steps">{{dictionary(Session::get('lang'))['on_girl_text']}}</h2> </div><ul class="step_ul"> <li><span class="step_text">{{dictionary(Session::get('lang'))['step1']}}</span></li><li><span class="step_text">{{dictionary(Session::get('lang'))['step2']}}</span></li><li><span class="step_text">{{dictionary(Session::get('lang'))['step3']}}</span></li><li><span class="step_text">{{dictionary(Session::get('lang'))['step4']}}</span></li><li><span class="step_text">{{dictionary(Session::get('lang'))['step5']}}</span></li><li><span class="step_text">{{dictionary(Session::get('lang'))['step6']}}<br><br></span></li></ul> </div><?php /*?><div class="media_main"> <div class="wrapper"> <div class="btns"> <span class="upload_file"><a href="#"><i class="fa fa-arrow-circle-o-up" aria-hidden="true"></i>UPLOAD FILE</a></span> <span class="clear_queue"><a href="#"><i class="fa fa-shopping-basket" aria-hidden="true"></i>CLEAR QUEUE</a></span> </div><span class="drop_file">Drop your file here</span> </div></div><div class="player"> <div class="wrapper"> <span class="player_img"><img src="images/player.png" alt="no-img"></span> </div></div><?php */?> <div class="clear"></div><div id="media_main"> <div id="upload-buttons-wrapper" class="wrapper"> <div class="btns"> <div id="pick-files" class="ui-button-success upload_file">Upload Files</div><div id="reset-all" class="ui-button-danger plupload_disabled clear_queue">Clear Queue</div></div></div><div class="player"> <div id="carousel-wrapper"> <div id="carousel-prev-wrapper"> <div id="carousel-prev" class="disabled"></div></div><div id="container"> <div id="carousel"> <ul id="filelist" class="plupload_filelist"></ul> </div></div><div id="carousel-next-wrapper"> <div id="carousel-next" class="disabled"></div></div></div></div><div id="content-wrapper"> <div id="content-progress"><div id="content-progress-status"></div></div><div id="content"></div></div></div></div><footer><div class="wrapper"> <span class="like_it">Like it? Share it!</span> <ul class="social_ul"> <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li><li><a href="#"><i class="fa fa-tumblr" aria-hidden="true"></i></a></li><li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li><li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li></ul> </div></footer>
@stop  